---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
  
  tasks:
    - name: Install software for repo management
      apt: name={{ item }} state=present
      with_items:
        - python-apt
        - python-pycurl

    - name: Add repo
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: Install packages
      apt: name={{ items }} state=present
      with_items:
        - git
        - curl
        - unzip
        - sendmail
        - apache2
        - php7.1-common
        - php7.1-cli
        - php7.1-dev
        - php7.1-gd
        - php7.1-curl
        - php7.1-json
        - php7.1-opcache
        - php7.1-xml
        - php7.1-mbstring
        - php7.1-pdo
        - php7.1-mysql
        - php-apcu
        - libpcre3-dev
        - libapache2-mod-php7.1
        - python-mysqldb48- mysql-server

    - name: Disable firewall
      service: name=ufw state=stopped

    - name: Start Apache MySQL PHP
      service: "name={{ item }} state=started"
      with_items:
        - apache2
        - mysql

    - name: Enable apache rewrite module
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: Add virtualhost
      tempfile:
        src: "templates/drupal.test.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: Symlink drupal virtualhosts to sites-enabled
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.test.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.test.conf"
        state: link
      notify: restart apache

    - name: Remove default virtualhost file
      file:
        path: "/etc/apache2/sites-enabled/000-default.conf"
        state: absent
      notify: restart apache

    - name: Adjust OpCache memory settings
      lineinfile:
        dest: "/etc/php/7.1/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
      notify: restart apache

    - name: Remove the MySql test db
      mysql_db: db=test state=absent

    - name: Create a db for Drupal
      mysql_db: "db={{ domain }} state=present"

    - name: Create User
      mysql_user:
        name: "{{ domain }}"
        password: "1234"
        priv: "{{ domain }}.*:ALL"
        host: localhost
        state: present

    - name: Download Composer Installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: run installer
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Move composer 
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        create=/usr/local/bin/composer

    - name: check out drush 
      git:
        repo: https://github.com/drush-ops/drush.git
        version: 8.x
        dest: /opt/drush

    - name: Install drush dependendecies with composer
      shell: >
        /usr/local/bin/composer install
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: Create drush bin symlink
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link

    - name: Check out Drupal Core to the Apache docroot
      git:
        repo: http://git.drupal.org/project/drupal.git
        version: "{{ drupal_core_version }}"
        dest: "{{ drupal_cor_path }}"

    - name: Install Drupal dependencies
      shell: >
        /usr/local/bin/composer/ install
        chdir={{ drupal_cor_path }}
        creates={{ drupal_core_path }}/vendor/autoload.php

    
        
      

   